In [1]:
import torch

In [2]:
x = torch.arange(12)
x.shape

torch.Size([12])

In [3]:
x.numel()

12

In [4]:
x.reshape(3, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [6]:
torch.randn(3, 4)

tensor([[ 0.4101, -1.6204,  1.3494,  0.3506],
        [ 0.0209,  1.6907, -0.4113, -1.4667],
        [ 0.7755,  1.7836, -0.2311,  0.2397]])

In [7]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [8]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [9]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [10]:
x.sum()

tensor(15.)

In [11]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [12]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [13]:
x == y

tensor([False,  True, False, False])

In [14]:
x > y

tensor([False, False,  True,  True])

In [15]:
x < y

tensor([ True, False, False, False])