In [10]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [11]:
x.requires_grad_(True)
print(x.grad)

None


In [12]:
import torch
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4 * x

tensor([True, True, True, True])

In [15]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
x.grad.zero_()
y=x*x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [17]:
y.backward(torch.ones(len(x)))
x.grad

tensor([0., 2., 4., 6.])

In [18]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [19]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [20]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(), requires_grad=True)
d = f(a)

In [26]:
d
d.backward()
d.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [25]:
a.grad == d/a
d/a

tensor(8192., grad_fn=<DivBackward0>)